categories:
  - sms
  - mms
  - whatsapp
  - rcs
  - number-lookup
  - verification
  - voice
  - video
  - tutorials
  - contributing-guidelines
  - release-notes

filters:
  hostedFiles:
    baseUrl: https://sinch.github.io/docs/
  footer:
    template: templates/footer.mustache
    baseUrl: https://github.com/sinch/docs/blob/master/docs/